id: AD3D88E0D
title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
  of the Land of Snow'
type: translation
pechas:
- I828B1F8D
- IA565CA9B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:13:05.514497
  last_modified_at: 2023-01-04 12:13:05.514502
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I828B1F8D/916A: C98C
  IA565CA9B/6696: C98C
